name: Git Action Test Flow

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image for my project 
      run: docker build --tag daeun17/gitaction:latest .


    - name: Login to DockerHUb 
      run: docker login -u ${{secrets.DOCKER_NAME}} -p ${{secrets.DOCKER_PASSWORD}}
    
    - name: Push the Docker image to the repository 
      run: docker push daeun17/gitaction:latest
